### ISSUE TITLE
not working AE CC 2018 

### ISSUE THREAD

**Issue by dev31** [Inlife/nexrender-boilerplate#12]
It seems not working in AE CC 2018
There is no result file in folders: \result\, \temprJDvktdUG\

```
Error message: ENOENT: no such file or directory, stat 'C:\Users\devua\nexrender-boilerplate\temp\rJDvktdUG\result.avi'
{ Error: ENOENT: no such file or directory, stat 'C:\Users\devua\nexrender-boilerplate\temp\rJDvktdUG\result.avi'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\devua\\nexrender-boilerplate\\temp\\rJDvktdUG\\result.avi' }
```

**Comment by inlife** [comment]
this is related to ae 2018 not having h264 support
just make sure you provide into project config
```
outputExt: 'avi'
```

**Comment by dev31** [comment]
The same result:

```
C:\Users\devua\nexrender-boilerplate>node start.js
Started local static server at port: 23234
Project {
  uid: 'rJ4YqJcIz',
  state: 'queued',
  template: 'project.aepx',
  composition: 'main',
  type: 'default',
  assets:
   [ { type: 'project',
       name: 'project.aepx',
       src: 'http://localhost:23234/assets/nm05ae12-q.aepx' },
     { type: 'image',
       name: 'background.jpg',
       src: 'http://localhost:23234/assets/2016-aug-deep.jpg',
       filters: [Array] },
     { type: 'image',
       name: 'nm.png',
       src: 'http://localhost:23234/assets/nm.png' },
     { type: 'audio',
       name: 'audio.mp3',
       src: 'http://localhost:23234/assets/deep_60s.mp3' },
     { type: 'script',
       name: 'data.js',
       src: 'http://localhost:23234/assets/2016-aug-deep.js' } ],
  actions: [],
  settings:
   { outputModule: 'h264',
     startFrame: 0,
     endFrame: 3600,
     outputExt: 'avi' },
  errorMessage: null,
  callbacks: {},
  ticker: null,
  api: null,
  error: null }
[rJ4YqJcIz] setting up project...
[rJ4YqJcIz] downloading assets...
[rJ4YqJcIz] renaming assets...
[rJ4YqJcIz] filtering image assets...
[rJ4YqJcIz] patching project...
[rJ4YqJcIz] rendering project...
[rJ4YqJcIz] verifying project...
//--------------------------
[rJ4YqJcIz] project failed
//--------------------------

Error message: ENOENT: no such file or directory, stat 'C:\Users\devua\nexrender-boilerplate\temp\rJ4YqJcIz\result.avi'
{ Error: ENOENT: no such file or directory, stat 'C:\Users\devua\nexrender-boilerplate\temp\rJ4YqJcIz\result.avi'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\devua\\nexrender-boilerplate\\temp\\rJ4YqJcIz\\result.avi' }
```

**Comment by inlife** [comment]
did you check your temp folder, was there any generated file ?

**Comment by dev31** [comment]
Yes, there is a new folder inside temp each rendering with all assets but witout result.avi
And the result path is empty (except readme.txt)

**Comment by dev31** [comment]
I have installed QuickTime Alternative and use h264 codec

**Comment by inlife** [comment]
seems like aerender doesnt want to generate the file, you need to check the after effects log itself to see the reason

**Comment by dev31** [comment]
@inlife Do you mean AE log or nexrender log?
Unfortunately the same for avi.
![nexrender-boilerplate -error](https://user-images.githubusercontent.com/12541902/36017883-6d39bcde-0d71-11e8-939b-1ce3e07a5142.jpg)
But another file there are
![hjo1_r9lz](https://user-images.githubusercontent.com/12541902/36017956-ca78cbb0-0d71-11e8-8bd3-7a7e2a39f786.jpg)

**Comment by inlife** [comment]
are you sure it spawns the rendering process right ?
there is supposed to be output information created by aerender 
where is it ?

**Comment by shaileshsitestrokes** [comment]
Hii 

I am also getting same error on AE 2018?

Error message: ENOENT: no such file or directory, stat 'D:\nodejs\first\nexrender-boilerplate\temp\Dl1OxsiLB\result.avi'
{ [Error: ENOENT: no such file or directory, stat 'D:\nodejs\first\nexrender-boilerplate\temp\Dl1OxsiLB\result.avi']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   'D:\\nodejs\\first\\nexrender-boilerplate\\temp\\Dl1OxsiLB\\result.avi' }

please help me to solve this issue.

Thanks.

**Comment by rafaelboschini** [comment]
Change outputExt to avi and remove outputModule works form me, but....the result file has 9gb :(
I need to render in mp4.

**Comment by inlife** [comment]
@rafaelboschini i suggest you to checkout the latest version of the https://github.com/inlife/nexrender
it has built-in ffmpeg encoder, that allows you to convert your temp avi/mov result into mp4, or any other format with much less used size
