### ISSUE TITLE
Custom output name

### ISSUE THREAD

**Issue by rhernandog** [Inlife/nexrender-boilerplate#15]
Is it possible to set a specific name for the output file instead of the one auto generated?. Also is worth mentioning that the idea is to run an automated node client app that will take different files to create the outputs, so we'd like to use our own naming convention for the final file.

Thanks!!

**Comment by inlife** [comment]
Hello,

No, its not possible to do it via settings, however you could just add a file rename method call right there: https://github.com/inlife/nexrender-boilerplate/blob/master/start.js#L100-L104

**Comment by rhernandog** [comment]
Hi and thanks for the prompt answer.

Yep that's what I've been doing so far. I get the project **uid** and then use that with node's file system to rename the file.

Have a nice one and thanks again!!
