### ISSUE TITLE
No support for AE CC 2018

### ISSUE THREAD

**Issue by deadlocked247** [Inlife/nexrender-boilerplate#18]
Expressions do not work with the latest AE, they are saved differently to the xml file

**Comment by inlife** [comment]
there is an issue in the original repo, where we were discussing this problem, and ways to fix it
https://github.com/inlife/nexrender/issues/46

**Comment by deadlocked247** [comment]
@inlife I forked your repo and I got a version working that supports handlebar templating inside expressions 

data.js (asset)
`var data = { text: 'text' }`

project.apex (expression on text layer)
`{{ data.text }}`

This evaluates inside the template file to 
`"text"`

https://github.com/deadlocked247/nexrender

**Comment by inlife** [comment]
oh damn, thats pretty cool!
however seems like the link isn't available anymore :/
