### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by Ariel2013** [Inlife/nexrender-boilerplate#19]
exo me, I got an error like this for hours.
```
$ node start.js
Started local static server at port: 23234
Project {
  uid: 'UVFgZwFL-',
  state: 'queued',
  template: 'project.aepx',
  composition: 'main',
  type: 'default',
  assets:
   [ { type: 'project',
       name: 'project.aepx',
       src: 'http://localhost:23234/assets/nm05ae12.aepx' },
     { type: 'image',
       name: 'background.jpg',
       src: 'http://localhost:23234/assets/2016-aug-deep.jpg',
       filters: [Array] },
     { type: 'image',
       name: 'nm.png',
       src: 'http://localhost:23234/assets/nm.png' },
     { type: 'audio',
       name: 'audio.mp3',
       src: 'http://localhost:23234/assets/deep_60s.mp3' },
     { type: 'script',
       name: 'data.js',
       src: 'http://localhost:23234/assets/2016-aug-deep.js' } ],
  actions: [],
  settings:
   { outputModule: 'test',
     startFrame: 0,
     endFrame: 3600,
     outputExt: 'mov' },
  errorMessage: null,
  callbacks: {},
  ticker: null,
  api: null,
  error: null }
[UVFgZwFL-] setting up project...
[UVFgZwFL-] downloading assets...
[UVFgZwFL-] renaming assets...
[UVFgZwFL-] filtering image assets...
[UVFgZwFL-] patching project...
[UVFgZwFL-] rendering project...
[UVFgZwFL-] verifying project...
--------------------------
[UVFgZwFL-] project failed
--------------------------

Error message: ENOENT: no such file or directory, stat 'temp/UVFgZwFL-/result.mov'
{ Error: ENOENT: no such file or directory, stat 'temp/UVFgZwFL-/result.mov'
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'temp/UVFgZwFL-/result.mov' }
```
what I did:
1. clone the project
2. change the aerender path
3. create a new outputModule in AE named 'test', and change outputExt to 'mov'
4. start

PS: my workmate works well as I do. Orz.

my env: MacOS 10.14.1, AE2018/2014.

I'm new for AE, thanks for any help.  Orz

**Comment by Ariel2013** [comment]
this is output result:
![image](https://user-images.githubusercontent.com/8024910/48040888-d42f4d00-e1b5-11e8-8b94-9cf6eca9651a.png)

**Comment by inlife** [comment]
that is interestingly weird
for some reason AE isnt outputting any file, maybe some file read/write permission issues?

**Comment by Ariel2013** [comment]
> that is interestingly weird
> for some reason AE isnt outputting any file, maybe some file read/write permission issues?

thanks for reply.

Two of my workmates work well. It should be my own problem.

I try `sudo` just now, failed still. /(ㄒoㄒ)/

**Comment by inlife** [comment]
try to render manually, via AE, maybe you will see some errors or something like that

**Comment by Ariel2013** [comment]
Thanks. I'll try it.

**Comment by Ariel2013** [comment]
i try to run aerender in command line,  got error.
![image](https://user-images.githubusercontent.com/8024910/48250678-14066680-e43a-11e8-895e-68d6830d687d.png)
i actually cannot google it.

but render via AE APP works well.

im really at a loss. (￣o￣) .

**Comment by inlife** [comment]
seems like something is wrong with your particular AE installation somehow

**Comment by inlife** [comment]
seems to me that it might be related to the scripts folder, have you ever edited/added some scripts to AE ?

**Comment by Ariel2013** [comment]
> seems to me that it might be related to the scripts folder, have you ever edited/added some scripts to AE ?

im not familiar with AE, maybe i did something wrong while installing.

ill try to reinstall it later.

thank u so much. :)

**Comment by akashtsitestrokes** [comment]
Hello inlife,

I am also getting the same error.
The output file is not generating.

Thanks.

**Comment by inlife** [comment]
@akashtsitestrokes can you check what errors does your AE report when you attempt to render ?
