### ISSUE TITLE
PostRender Action

### ISSUE THREAD

**Issue by naveedaziz** [Inlife/nexrender-boilerplate#20]
Can you please tell me about post render as current file size is 9GB. I need to know how to run post render or how i can reduce size. Thanks

**Comment by inlife** [comment]
Yep, the docs with examples are here:
https://github.com/inlife/nexrender#actions
and here:
https://github.com/inlife/nexrender/tree/master/packages/nexrender-action-encode

**Comment by naveedaziz** [comment]
Thanks for all support. I have done all using your packages/worker and packages/server.
It helps me creating final render. :-)

**Comment by inlife** [comment]
Glad to hear!

**Comment by naveedaziz** [comment]
Dear, After doing all process successfully, my Adobe After Effects is
stuck at this screen.

[image: image.png]

Can you tell me whats the issue and why its not working? It occurs when i
render using nexrender.

**Comment by naveedaziz** [comment]
All the menus in the software is grey out and not allowing to do anything
or create any new project. I am using After Effects CC 2018 and also tried
on 2017 and has same issue both on Mac and Windows PC

**Comment by inlife** [comment]
Try removing `ae_render_only_node.txt`:
https://helpx.adobe.com/after-effects/kb/accidental-render-node-launch-ae.html
EDIT: pasted wrong link :D

**Comment by naveedaziz** [comment]
Thanks, it works.
