### ISSUE TITLE
Help needed in Output module setting

### ISSUE THREAD

**Issue by jdevelopervimal** [Inlife/nexrender-boilerplate#6]
I'm new in after effect and
I'm faceing Error message: ENOENT: no such file or directory, stat 'E:\node\nexrender-ex\temp\SkvIaVZFW\result.avi' 
issue so please tell me about  "**Output module setting**"

**Comment by inlife** [comment]
Please read all info about both
Output module, and output extension
https://github.com/Inlife/nexrender/wiki/Project-model#settingsoutputmodule

And follow the links to AE site, to read more too
